export const sliderItems = [
  {
    _id: 1,
    image: "./images/slider/1.jpg",
  },
  {
    _id: 2,
    image: "./images/slider/2.jpg",
  },
  {
    _id: 3,
    image: "./images/slider/3.jpg",
  },
  {
    _id: 4,
    image: "./images/slider/4.jpg",
  },
];
export const category = [
  {
    _id: 1,
    title: "Men",
    image: "/images/category/men.jpg",
  },
  {
    _id: 2,
    title: "Women",
    image: "/images/category/women.jpg",
  },
  {
    _id: 3,
    title: "Kids",
    image: "/images/category/kids.webp",
  },
];

export const products = [
  {
    _id: 1,
    title: "Product 1",
    slug: "product1",
    desc: "Description for Product 1",
    category: "Men",
    image: "/images/products/1.webp",
    image1: "/images/products/2.webp",
    image2: "/images/products/3.webp",
    image3: "/images/products/4.webp",
    countInStock: 0,
    price: "28.00",
  },
  {
    _id: 2,
    title: "Product 2",
    slug: "product2",
    desc: "Description for Product 2",
    category: "Women",
    image: "/images/products/5.webp",
    image1: "/images/products/6.webp",
    image2: "/images/products/7.webp",
    image3: "/images/products/8.webp",
    countInStock: 9,
    price: "17.00",
  },
  {
    _id: 3,
    title: "Product 3",
    slug: "product3",
    desc: "Description for Product 3",
    category: "Men",
    image: "/images/products/9.jpg",
    image1: "/images/products/10.jpg",
    image2: "/images/products/11.jpg",
    image3: "/images/products/12.webp",
    countInStock: 3,
    price: "29.99",
  },
  {
    _id: 4,
    title: "Product 4",
    slug: "product4",
    desc: "Description for Product 4",
    category: "Women",
    image: "/images/products/13.jpg",
    image1: "/images/products/14.jpg",
    image2: "/images/products/15.jpg",
    image3: "/images/products/16.jpg",
    countInStock: 4,
    price: "40.00",
  },
  {
    _id: 5,
    title: "Product 5",
    slug: "product5",
    desc: "Description for Product 4",
    category: "Women",
    image: "/images/products/17.jpg",
    image1: "/images/products/18.jpg",
    image2: "/images/products/19.jpg",
    image3: "/images/products/20.jpg",
    countInStock: 11,
    price: "35.00",
  },
  {
    _id: 6,
    title: "Product 6",
    slug: "product6",
    desc: "Description for Product 4",
    category: "Kids",
    image: "/images/products/25.webp",
    image1: "/images/products/26.webp",
    image2: "/images/products/27.webp",
    image3: "/images/products/28.webp",
    countInStock: 12,
    price: "26.00",
  },
  {
    _id: 7,
    title: "Product 7",
    slug: "product7",
    desc: "Description for Product 4",
    category: "Kids",
    image: "/images/products/21.webp",
    image1: "/images/products/22.webp",
    image2: "/images/products/23.webp",
    image3: "/images/products/24.webp",
    countInStock: 15,
    price: "14.00",
  },
  {
    _id: 8,
    title: "Product 8",
    slug: "product8",
    desc: "Description for Product 8",
    category: "Men",
    image: "/images/products/30.webp",
    image1: "/images/products/31.webp",
    image2: "/images/products/32.webp",
    image3: "/images/products/33.webp",
    countInStock: 5,
    price: "17.00",
  },
  {
    _id: 9,
    title: "Product 9",
    slug: "product9",
    desc: "Description for Product 9",
    category: "Men",
    image: "/images/products/38.webp",
    image1: "/images/products/35.webp",
    image2: "/images/products/36.webp",
    image3: "/images/products/37.webp",
    countInStock: 15,
    price: "30.00",
  },

  {
    _id: 11,
    title: "Product 11",
    slug: "product11",
    desc: "Description for Product 11",
    category: "Men",
    image: "/images/products/43.jpg",
    image1: "/images/products/44.jpg",
    image2: "/images/products/45.jpg",
    image3: "/images/products/46.jpg",
    countInStock: 15,
    price: "34.00",
  },

  {
    _id: 12,
    title: "Product 12",
    slug: "product12",
    desc: "Description for Product 12",
    category: "Men",
    image: "/images/products/47.jpg",
    image1: "/images/products/48.jpg",
    image2: "/images/products/49.jpg",
    image3: "/images/products/50.jpg",
    countInStock: 15,
    price: "29.99",
  },
];
